project_id: '670328'
preserve_hierarchy: true
base_path: '.'

files:
  # Docs Markdown files
  # - source: '/docs/en/**/*.md'
  #   translation: '/docs/%two_letters_code%/%original_path%/%original_file_name%'
  - source: '/**/sources/*.strings'
    translation: "/**/translations/%osx_locale%/%original_file_name%"
